{application,phoenix_live_reload,
             [{registered,[]},
              {description,"Provides live-reload functionality for Phoenix"},
              {applications,[kernel,stdlib,elixir,logger,phoenix,fs]},
              {mod,{'Elixir.Phoenix.LiveReload',[]}},
              {vsn,"0.5.1"},
              {modules,['Elixir.Phoenix.LiveReload',
                        'Elixir.Phoenix.LiveReload.Channel',
                        'Elixir.Phoenix.LiveReload.Digest',
                        'Elixir.Phoenix.LiveReloader',
                        'Elixir.Phoenix.LiveReloader.Socket']}]}.